// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using act.core.data;

namespace act.core.data.Migrations
{
    [DbContext(typeof(ActDbContext))]
    partial class ActDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("act.core.data.BuildSpecification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("BuildSpecificationType")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<bool>("IncludeRemedyEmailList")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("OperatingSystemName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("OperatingSystemVersion")
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.Property<string>("Overview")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("OwnerEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Platform")
                        .HasColumnType("int");

                    b.Property<bool>("RunningCoreOs")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("WikiLink")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerEmployeeId");

                    b.HasIndex("ParentId");

                    b.ToTable("BuildSpecification");
                });

            modelBuilder.Entity("act.core.data.ComplianceResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<long>("InventoryItemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("OperatingSystemTestPassed")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("ResultId", "InventoryItemId")
                        .IsUnique();

                    b.HasIndex("EndDate", "Id", "InventoryItemId");

                    b.ToTable("ComplianceResult");
                });

            modelBuilder.Entity("act.core.data.ComplianceResultError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<long>("ComplianceResultId")
                        .HasColumnType("bigint");

                    b.Property<string>("LongMessage")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceResultId", "Code", "Name");

                    b.ToTable("ComplianceResultError");
                });

            modelBuilder.Entity("act.core.data.ComplianceResultTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ComplianceResultId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<int?>("PortType")
                        .HasColumnType("int");

                    b.Property<int>("ResultType")
                        .HasColumnType("int");

                    b.Property<bool>("ShouldExist")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceResultId", "ResultType", "PortType", "ShouldExist", "Name");

                    b.ToTable("ComplianceResultTest");
                });

            modelBuilder.Entity("act.core.data.Employee", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.Property<string>("PreferredName")
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<long?>("ReportingDirectorId")
                        .HasColumnType("bigint");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasColumnType("nchar(64)");

                    b.Property<long?>("SupervisorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReportingDirectorId");

                    b.HasIndex("SamAccountName")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.HasIndex("FirstName", "Id");

                    b.HasIndex("LastName", "Id");

                    b.HasIndex("PreferredName", "Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("act.core.data.Environment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ChefAutomateOrg")
                        .IsRequired()
                        .HasColumnType("varchar(16) CHARACTER SET utf8mb4")
                        .HasMaxLength(16);

                    b.Property<string>("ChefAutomateToken")
                        .IsRequired()
                        .HasColumnType("varchar(64) CHARACTER SET utf8mb4")
                        .HasMaxLength(64);

                    b.Property<string>("ChefAutomateUrl")
                        .IsRequired()
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(7) CHARACTER SET utf8mb4")
                        .HasMaxLength(7);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Environment");
                });

            modelBuilder.Entity("act.core.data.Function", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Function");
                });

            modelBuilder.Entity("act.core.data.Justification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BuildSpecificationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Color")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("JustificationText")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("JustificationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.HasIndex("BuildSpecificationId");

                    b.ToTable("Justification");
                });

            modelBuilder.Entity("act.core.data.Node", b =>
                {
                    b.Property<long>("InventoryItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuildSpecificationId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ChefNodeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ComplianceStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeactivatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("EnvironmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FailingSince")
                        .HasColumnType("datetime");

                    b.Property<string>("Fqdn")
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4")
                        .HasMaxLength(256);

                    b.Property<int>("FunctionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastComplianceResultDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("LastComplianceResultId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastEmailedOn")
                        .HasColumnType("datetime");

                    b.Property<long>("OwnerEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<int>("PciScope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("4");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nchar(4)");

                    b.Property<string>("RemedyGroupEmailList")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RemedyGroupName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("InventoryItemId");

                    b.HasIndex("BuildSpecificationId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("FunctionId");

                    b.HasIndex("OwnerEmployeeId");

                    b.HasIndex("Platform");

                    b.HasIndex("ProductCode");

                    b.HasIndex("Fqdn", "InventoryItemId");

                    b.HasIndex("PciScope", "InventoryItemId");

                    b.ToTable("Node");
                });

            modelBuilder.Entity("act.core.data.Port", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BuildSpecificationId")
                        .HasColumnType("bigint");

                    b.Property<int>("From")
                        .HasColumnType("int");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOutgoing")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("JustificationId")
                        .HasColumnType("bigint");

                    b.Property<int>("PortType")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<int?>("To")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildSpecificationId");

                    b.HasIndex("JustificationId");

                    b.ToTable("Port");
                });

            modelBuilder.Entity("act.core.data.Product", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nchar(4)");

                    b.Property<bool>("ExludeFromReports")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("Code");

                    b.HasIndex("Name");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("act.core.data.SoftwareComponent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BuildSpecificationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(512) CHARACTER SET utf8mb4")
                        .HasMaxLength(512);

                    b.Property<long?>("JustificationId")
                        .HasColumnType("bigint");

                    b.Property<int>("JustificationType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<bool>("NonCore")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PciScope")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.HasIndex("BuildSpecificationId");

                    b.HasIndex("JustificationId");

                    b.ToTable("SoftwareComponent");
                });

            modelBuilder.Entity("act.core.data.SoftwareComponentEnvironment", b =>
                {
                    b.Property<int>("EnvironmentId")
                        .HasColumnType("int");

                    b.Property<long>("SoftwareComponentId")
                        .HasColumnType("bigint");

                    b.HasKey("EnvironmentId", "SoftwareComponentId");

                    b.HasIndex("SoftwareComponentId");

                    b.ToTable("SoftwareComponentEnvironment");
                });

            modelBuilder.Entity("act.core.data.BuildSpecification", b =>
                {
                    b.HasOne("act.core.data.Employee", "Owner")
                        .WithMany("BuildSpecifications")
                        .HasForeignKey("OwnerEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("act.core.data.BuildSpecification", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("act.core.data.ComplianceResult", b =>
                {
                    b.HasOne("act.core.data.Node", "Node")
                        .WithMany("ComplianceResults")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("act.core.data.ComplianceResultError", b =>
                {
                    b.HasOne("act.core.data.ComplianceResult", "ComplianceResult")
                        .WithMany("Errors")
                        .HasForeignKey("ComplianceResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("act.core.data.ComplianceResultTest", b =>
                {
                    b.HasOne("act.core.data.ComplianceResult", "ComplianceResult")
                        .WithMany("Tests")
                        .HasForeignKey("ComplianceResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("act.core.data.Employee", b =>
                {
                    b.HasOne("act.core.data.Employee", "ReportingDirector")
                        .WithMany()
                        .HasForeignKey("ReportingDirectorId");

                    b.HasOne("act.core.data.Employee", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId");
                });

            modelBuilder.Entity("act.core.data.Justification", b =>
                {
                    b.HasOne("act.core.data.BuildSpecification", "BuildSpecification")
                        .WithMany("Justifications")
                        .HasForeignKey("BuildSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("act.core.data.Node", b =>
                {
                    b.HasOne("act.core.data.BuildSpecification", "BuildSpecification")
                        .WithMany("Nodes")
                        .HasForeignKey("BuildSpecificationId");

                    b.HasOne("act.core.data.Environment", "Environment")
                        .WithMany("Nodes")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("act.core.data.Function", "Function")
                        .WithMany("Nodes")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("act.core.data.Employee", "Owner")
                        .WithMany("Nodes")
                        .HasForeignKey("OwnerEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("act.core.data.Product", "Product")
                        .WithMany("Nodes")
                        .HasForeignKey("ProductCode");
                });

            modelBuilder.Entity("act.core.data.Port", b =>
                {
                    b.HasOne("act.core.data.BuildSpecification", "BuildSpecification")
                        .WithMany("Ports")
                        .HasForeignKey("BuildSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("act.core.data.Justification", "Justification")
                        .WithMany("Ports")
                        .HasForeignKey("JustificationId");
                });

            modelBuilder.Entity("act.core.data.SoftwareComponent", b =>
                {
                    b.HasOne("act.core.data.BuildSpecification", "BuildSpecification")
                        .WithMany("SoftwareComponents")
                        .HasForeignKey("BuildSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("act.core.data.Justification", "Justification")
                        .WithMany("SoftwareComponents")
                        .HasForeignKey("JustificationId");
                });

            modelBuilder.Entity("act.core.data.SoftwareComponentEnvironment", b =>
                {
                    b.HasOne("act.core.data.Environment", "Environment")
                        .WithMany("SoftwareComponentEnvironments")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("act.core.data.SoftwareComponent", "SoftwareComponent")
                        .WithMany("SoftwareComponentEnvironments")
                        .HasForeignKey("SoftwareComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
